name: Test

on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Install kindlegen
      run: |
        curl -L https://github.com/ibndias/papeer/releases/download/kindlegen/kindlegen_linux_2.6_i386_v2_9.tar.gz > kindlegen.tar.gz
        tar xzvf kindlegen.tar.gz
        chmod +x kindlegen
        mv kindlegen /usr/local/bin
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: make test
